services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8920:8920"
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ../midia:/media
    restart: unless-stopped